config/routes.rb
VideoApp::Application.routes.draw do

  get 'administration' => 'administrations#index', as: 'administration'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users


  resources :orders, only: [:new, :create, :index, :destroy]
  

  # resources :carts
  get 'carts/:id' => 'carts#show', as: 'cart'
  delete 'carts/:id' => 'carts#destroy'

  # resources :line_items
  post 'line_items' => 'line_items#create'

  root to: 'store#index'
  get 'store' => 'store#index', as: 'store'

  get "videos" => 'videos#index', as: 'videos'
  get "videos/new" => 'videos#new', as: 'new_video'
  get "videos/:id" => 'videos#show', as: 'video'
  get "videos/:id/edit" => 'videos#edit', as: 'edit_video'   
  post "videos" => "videos#create"
  put "videos/:id" => "videos#update"
  delete "videos/:id" => "videos#destroy"

 #I'm not using resources :videos and typing each route manually instead to refer to it easily
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :description, :poster, :price, :title, :video
  cattr_accessor :current_user

  mount_uploader :video, VideoUploader
  mount_uploader :poster, PosterUploader

  validates :price, :title, :video, presence: true

  validates :price, numericality:{greater_than_or_equal_to: 0.01, message: "must be a positive number",
                                allow_nil: false}
  validates :title, uniqueness: true

  validates :video, format: {with: /\.(mp4|ogv|ogg|webm)\Z/i,
                               message: 'must be a URL for mp4. ogg or webm video'}

  validates :poster,  format: {with: /\.(gif|jpg|png)\Z/i,
                        message: 'must be a URL for GIF, JPG or PNG image',
                        allow_blank: true}

  has_many :line_items
  
   before_destroy :ensure_not_referenced_by_any_line_item
  
  def image_placeholder
     poster_url || 'rouxbe.jpg'
  end

  def has_been_paid?
    current_user.admin ? true : current_user.ordered_video(self)
  end

  private

    def ensure_not_referenced_by_any_line_item
    	line_items.empty?.tap { |i| errors.add(:base, "Line Items present") unless i}
    end                      
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
before_filter :authorize_admin_only, except: [:show]
before_filter :authorize_admin_and_those_who_ordered, only: [:show]

  def index
    @videos = Video.all
  end


  def new
    @video = Video.new
  end


  def show
    @video = Video.find(params[:id])
  end


  def edit
    @video = Video.find(params[:id])
  end


  def create
    @video = Video.new(params[:video])
    if @video.save
      redirect_to video_url(@video), notice: "You successfully created a video"
    else
      render :new
    end
  end


  def destroy
    video = Video.find(params[:id])
    video.destroy
    redirect_to videos_url
  end


  def update
    @video = Video.find(params[:id])
    if @video.update_attributes(params[:video])
      redirect_to video_url(@video), notice: "You successfully updated the video"
    else
      render :edit
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.haml
= form_for @video, html: {multipart: true} do |f| 
  - if @video.errors.any?
    %h2
      = pluralize(@video.errors.count, "Error")
      %br/
      The video couldn't be saved
    %ul
      - @video.errors.full_messages.each do |error|
        %li= error

  %fieldset
    %legend Enter the video details
    = f.label :title
    = f.text_field :title
    %br/
    = f.label :description
    = f.text_area  :description, rows: 6
    %br/
    = f.label :video
    = f.file_field :video
    %br/
    %br/
    = f.label :poster
    = f.file_field :poster
    %br/
    %br/
    = f.label :price
    = f.number_field :price
    %br/
    - if params[:id]
      = f.submit 'Update Video', class: "btn btn-primary"
    - else
      = f.submit 'Create Video', class: "btn btn-primary"

app/views/videos/edit.html.haml
%h1 
  Editing
  = @video.title

= render 'form'

= link_to 'Back', videos_path

app/views/videos/index.html.haml
= flash[:notice] if flash[:notice]
%h1 Videos Administration
%h6.video_nbr
  = pluralize @videos.size, 'Video'
= link_to "Add A New Video",  new_video_path, class: ".btn btn-success space-link"
- @videos.each do |video|
  %article
    %table.video_table
      %tr
        %td
          = video_tag(video.video_url.to_s, poster: video.image_placeholder, controls: true, autobuffer: true, class: 'video_thumbnail')
        %td
          %dl
            %dt
              = link_to video.title, video_path(video)
            %dd
              = video.description
        %td
          = link_to 'Show', video_path(video), class: ".btn btn-primary space-link"
          %br
          %br
          = link_to 'Edit',  edit_video_path(video), class: ".btn btn-inverse space-link"
          %br
          %br
          = link_to 'Destroy', video_path(video),class: ".btn btn-danger space-link", method: :delete, data: {confirm: 'Are you sure?'}

app/views/videos/new.html.haml
%h1 Add New Video

= render 'form'

= link_to 'Back', videos_path

app/views/videos/show.html.haml
= flash[:notice] if flash[:notice]
%h1
  = @video.title
%article
  %table
    %tr
      %td
        = video_tag(@video.video_url.to_s, poster: @video.image_placeholder, controls: true, autobuffer: true, size: "640x480")
      %td
        %dl
          %dt
            = link_to @video.title, video_path(@video)
          %dd
            = truncate @video.description, length: 140, separator: ' '
      - if current_user && current_user.admin
        %td
          = link_to 'Back', videos_path, class: ".btn btn-primary space-link"
          %br
          %br
          = link_to 'Edit',  edit_video_path(@video), class: ".btn btn-inverse space-link"
          %br
          %br
          = link_to 'Destroy', @video, class: ".btn btn-danger space-link", method: :delete, data:{confirm: 'Are you sure?'} 